name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - feature/*

  jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        # Compilation/Build du projet
        - name: Build Project
          run: |
            docker build -t mon-projet-python:latest .
            docker run mon-projet-python:latest

        # Construction de l'image Docker
        - name: Build Docker Image
          run: docker build -t mon-projet-python:latest .

        # Exécution des tests unitaires
        - name: Run Unit Tests
          run: |
            # Ajoutez vos commandes pour exécuter les tests unitaires

        # Poussez l'image Docker vers le registre
        - name: Push Docker Image
          run: |
            echo "DOCKER_HUB_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker push mon-projet:latest
