name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - feature/*

  jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        # Compilation/Build du projet
        - name: Build Project
          run: |
            # Ajoutez vos commandes de build ici
            # Par exemple: ./gradlew build si vous utilisez Gradle

        # Construction de l'image Docker
        - name: Build Docker Image
          run: docker build -t mon-projet:latest .

        # Exécution des tests unitaires
        - name: Run Unit Tests
          run: |
            # Ajoutez vos commandes pour exécuter les tests unitaires
            # Par exemple: ./gradlew test si vous utilisez Gradle

        # Poussez l'image Docker vers le registre
        - name: Push Docker Image
          run: |
            echo "DOCKER_HUB_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker push mon-projet:latest
